name: Firebase Deploy

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18.x (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Firebase CLI (Stable version)
        run: npm install -g firebase-tools@12.x  # Pin to the 12.x version for stability

      - name: Authenticate with Firebase using Service Account
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASEADMIN }}
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS > ~/firebase_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=~/firebase_key.json

      - name: Deploy to Firebase
        run: firebase deploy --project rickgomez223
