name: Firebase Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ensure you use a compatible Node.js version

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT_KEY > "${HOME}/firebase_key.json"
          firebase auth:login --token "$(firebase functions:config:get | jq -r .token)"
          
      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/firebase_key.json"
        run: firebase deploy --project rickgomez223
